services:
  - type: web
    name: motherboard-assistant-api
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
